### ISSUE TITLE
add persona to github

### ISSUE THREAD

**Issue by shalcrackzzz** [shalcrackzzz/gitissues#1]

**Comment by shalcrackzzz** [comment]
hello there

**Comment by shalcrackzzz** [comment]
@azcruze hi there

**Comment by azcruze** [comment]
hey shalzzzzzzzzzzzz

**Comment by shalcrackzzz** [comment]
hoiii

**Comment by azcruze** [comment]
![github-app-tips](https://github.com/shalcrackzzz/gitissues/assets/153887343/2f6e8d5f-43c2-45a8-94c3-c588c6d78002)

**Comment by shalcrackzzz** [comment]
https://www.bing.com/images/search?view=detailV2&ccid=%2fpQhCJLW&id=7B4CEAB7AF785761E3EBE479164514B4DCBEC57E&thid=OIP._pQhCJLW-ALktUHnyqg1lQAAAA&mediaurl=https%3a%2f%2fgithub.githubassets.com%2fimages%2fmodules%2fsite%2fissues%2fillo%2fissues-board.png&exph=284&expw=474&q=How+do+I+use+GitHub+issues%3f&simid=607996988440255954&FORM=IRPRST&ck=A9A0A47854393704AEE1AF50AF187C3A&selectedIndex=24&itb=0

**Comment by shalcrackzzz** [comment]
how was your experience?
